# Title

In [ ]:
import numpy as np
from typing import Union

Setup a class for the Jacobi algorithm

In [2]:
class Jacobi:
	def __init__(self, *args, **kwargs) -> None:
		self.x = None	
		self.name = "Jacobi Iteration"	
		
	def iteration(self, x, b, L, U, D):
		self.x = np.matmul(np.linalg.inv(D), (b - np.matmul((L + U), x)))
		return self.x

Define the Gauss-Seidel iteration

In [3]:
class Gauss_Seidel:
	def __init__(self, *args, **kwargs) -> None:
		self.x = None
		self.name = "Gauss-Seidel Iteration"
		pass
	
	def iteration(self, x, b, L, U, D):
		self.x = np.matmul(np.linalg.inv(D + L), (b - np.matmul(U, x)))
		return self.x

Define the SOR iteration

In [4]:
class Successive_Overrelaxation:
	def __init__(self, *args, **kwargs) -> None:
		self.x = None
		self.name = "Successive Overrelaxation"
		self.w = kwargs["w"]
		print("w: ", self.w)
	
	def iteration(self, x, b, L, U, D):
		first_part = np.linalg.inv(((1.0 / self.w) * D) + L)	
		second_part = b - np.matmul((U + (1 - (1 / self.w)) * D), x)
		self.x = np.matmul(first_part, second_part)
		return self.x 

Interface through which the algorithms will be applied:

In [5]:
class Interface:
	def __init__(self, 
	      		 A: np.matrix, 
				 x: np.matrix, 
				 b: np.matrix,
				 algo: Union[Jacobi, Gauss_Seidel, Successive_Overrelaxation],
				 w: float = None) -> None:
		
		self.A = A
		self.x = x
		self.b = b
		self.D = np.diag(np.diag(A))	# Automating extraction of diagonal
		self.L = np.tril(A) - self.D	# Extract lower triangular part
		self.U = np.triu(A) - self.D	# Extract upper triangular part
		self.step = 0					# Keep track of step number
		self.w = w						# Used for SOR
		self.algo = algo(w = w)			# Switch between algorithms here

	def iteration(self, step_count = True):				# Apply chosen algorithm
		self.x = self.algo.iteration(x = self.x, b = self.b, L = self.L, U = self.U, D = self.D)
		if (step_count == True):
			self.step += 1
		return self.x
	
	def iterate_n_times(self, steps = 5):
		i = 0
		while (i < steps):
			self.step += 1
			self.print_step()
			self.iteration(step_count=False)
			self.print_x()
			i += 1

	def print_step(self):					
		print(f"{self.algo.name}::Step {self.step}:")

	def print_values(self):					
		self.print_step()
		print("A: \n", self.A)
		print()
		print("x: \n", self.x)
		print()
		print("b: \n", self.b)
		print()
		print("D: \n", self.D)
		print()
		print("D inverse: \n", np.linalg.inv(self.D))
		print()
		print("L: \n", self.L)
		print()
		print("U: \n", self.U)
		print()
	
	def print_x(self):
		print("x: \n", self.x)
		print()		

Compute Jacobi scheme

In [6]:
A = np.matrix([[5, -2, 1],
		    	   [-3, 9, 1],
				   [2, -1, -7]])
b = np.transpose(np.matrix([-1, 2, 3]))	
x0 = np.transpose(np.matrix([0, 0, 0]))	
num_steps = 10
jacobi = Interface(A, x0, b, Jacobi)	
jacobi.print_values()
jacobi.iterate_n_times(num_steps)

Jacobi Iteration::Step 0:
A: 
 [[ 5 -2  1]
 [-3  9  1]
 [ 2 -1 -7]]

x: 
 [[0]
 [0]
 [0]]

b: 
 [[-1]
 [ 2]
 [ 3]]

D: 
 [[ 5  0  0]
 [ 0  9  0]
 [ 0  0 -7]]

D inverse: 
 [[ 0.2         0.          0.        ]
 [ 0.          0.11111111  0.        ]
 [-0.         -0.         -0.14285714]]

L: 
 [[ 0  0  0]
 [-3  0  0]
 [ 2 -1  0]]

U: 
 [[ 0 -2  1]
 [ 0  0  1]
 [ 0  0  0]]

Jacobi Iteration::Step 1:
x: 
 [[-0.2       ]
 [ 0.22222222]
 [-0.42857143]]

Jacobi Iteration::Step 2:
x: 
 [[-0.02539683]
 [ 0.2031746 ]
 [-0.51746032]]

Jacobi Iteration::Step 3:
x: 
 [[-0.0152381 ]
 [ 0.2712522 ]
 [-0.46485261]]

Jacobi Iteration::Step 4:
x: 
 [[ 0.0014714 ]
 [ 0.26879315]
 [-0.47167549]]

Jacobi Iteration::Step 5:
x: 
 [[ 0.00185236]
 [ 0.27512108]
 [-0.46655005]]

Jacobi Iteration::Step 6:
x: 
 [[ 0.00335844]
 [ 0.27467857]
 [-0.4673452 ]]

Jacobi Iteration::Step 7:
x: 
 [[ 0.00334047]
 [ 0.27526895]
 [-0.46685167]]

Jacobi Iteration::Step 8:
x: 
 [[ 0.00347791]
 [ 0.27520812]
 [-0.46694114]]


In [7]:
gsi = Interface(A, x0, b, Gauss_Seidel)
gsi.print_values()
gsi.iterate_n_times(num_steps)

Gauss-Seidel Iteration::Step 0:
A: 
 [[ 5 -2  1]
 [-3  9  1]
 [ 2 -1 -7]]

x: 
 [[0]
 [0]
 [0]]

b: 
 [[-1]
 [ 2]
 [ 3]]

D: 
 [[ 5  0  0]
 [ 0  9  0]
 [ 0  0 -7]]

D inverse: 
 [[ 0.2         0.          0.        ]
 [ 0.          0.11111111  0.        ]
 [-0.         -0.         -0.14285714]]

L: 
 [[ 0  0  0]
 [-3  0  0]
 [ 2 -1  0]]

U: 
 [[ 0 -2  1]
 [ 0  0  1]
 [ 0  0  0]]

Gauss-Seidel Iteration::Step 1:
x: 
 [[-0.2       ]
 [ 0.15555556]
 [-0.50793651]]

Gauss-Seidel Iteration::Step 2:
x: 
 [[-0.03619048]
 [ 0.26659612]
 [-0.47699672]]

Gauss-Seidel Iteration::Step 3:
x: 
 [[ 0.00203779]
 [ 0.27590112]
 [-0.46740365]]

Gauss-Seidel Iteration::Step 4:
x: 
 [[ 0.00384118]
 [ 0.27543635]
 [-0.466822  ]]

Gauss-Seidel Iteration::Step 5:
x: 
 [[ 0.00353894]
 [ 0.27527098]
 [-0.46688473]]

Gauss-Seidel Iteration::Step 6:
x: 
 [[ 0.00348534]
 [ 0.27526008]
 [-0.46689849]]

Gauss-Seidel Iteration::Step 7:
x: 
 [[ 0.00348373]
 [ 0.27526108]
 [-0.46689909]]

Gauss-Seidel Iteration::Step 

In [8]:
print("Performing some steps of Successive Overrelaxation...")
sor = Interface(A, x0, b, w = 1.1, algo = Successive_Overrelaxation)
sor.print_values()
sor.iterate_n_times(num_steps)

Performing some steps of Successive Overrelaxation...
w:  1.1
Successive Overrelaxation::Step 0:
A: 
 [[ 5 -2  1]
 [-3  9  1]
 [ 2 -1 -7]]

x: 
 [[0]
 [0]
 [0]]

b: 
 [[-1]
 [ 2]
 [ 3]]

D: 
 [[ 5  0  0]
 [ 0  9  0]
 [ 0  0 -7]]

D inverse: 
 [[ 0.2         0.          0.        ]
 [ 0.          0.11111111  0.        ]
 [-0.         -0.         -0.14285714]]

L: 
 [[ 0  0  0]
 [-3  0  0]
 [ 2 -1  0]]

U: 
 [[ 0 -2  1]
 [ 0  0  1]
 [ 0  0  0]]

Successive Overrelaxation::Step 1:
x: 
 [[-0.22      ]
 [ 0.16377778]
 [-0.56630794]]

Successive Overrelaxation::Step 2:
x: 
 [[-0.00135003]
 [ 0.29678707]
 [-0.46186004]]

Successive Overrelaxation::Step 3:
x: 
 [[ 0.01233052]
 [ 0.27573649]
 [-0.46469728]]

Successive Overrelaxation::Step 4:
x: 
 [[ 0.0023244 ]
 [ 0.27451941]
 [-0.46736708]]

Successive Overrelaxation::Step 5:
x: 
 [[ 0.00337686]
 [ 0.27535333]
 [-0.46690037]]

Successive Overrelaxation::Step 6:
x: 
 [[ 0.00353586]
 [ 0.2752712 ]
 [-0.46688417]]

Successive Overrelaxation::Ste